---
gateway: 10.0.200.254
netmask: 255.255.255.0
gateway2: 
netmask2: 

# VMWare default ens192
# KVM default ens3
# Libvirt default enp1s0
# Intel NUC default eno1
interface: ens192
interface2: 
dns: 
  - 192.168.10.23
  - 
webserver_url: 10.0.200.254
webserver_port: 8080

# Ignition subpath in http server (optionnal, defaults to nothing)
webserver_ignition_path: ocp4

# Drive to install RHCOS
# Libvirt - can be vda
install_drive: sda

# Timeout for selection menu during first boot
# '-1' for infinite timeout. Default '10'
boot_timeout: 10

# Chose the binary architecture
# x86_64 or ppc64le
arch: "x86_64"

#ocp_version: 4.5.4
ocp_version: 4.9.0
#iso_checksum: 48e3cbbb632795f1cb4a5713d72c30b438a763468495db69c0a2ca7c7152856a
iso_checksum: 0e92c3ad698ef68057011f7cc5b9fd07356b8711a55f735aaae22c91b996c96e
iso_checksum_ppc64: ff3ef20a0c4c29022f52ad932278b9040739dc48f4062411b5a3255af863c95e
#iso_name: rhcos-{{ ocp_version }}-x86_64-installer.x86_64.iso
iso_name: rhcos-{{ ocp_version }}-x86_64-live.x86_64.iso
iso_name_ppc64: rhcos-{{ ocp_version }}-ppc64le-installer.ppc64le.iso
rhcos_bios: rhcos-{{ ocp_version }}-x86_64-metal.x86_64.raw.gz
...
